"""Metamorphic properties on random problems, generated by Hypothesis.

Each property must hold whatever the correct answer is, so a failure points
at the implementation without needing an oracle. The last property does use
an oracle: the independent ordered-outcome solver in ``test_calibration``.
"""

import numpy as np
from hypothesis import given, settings
from hypothesis import strategies as st

from fairlex import calibration
from fairlex.calibration import leximin_weights

from .test_calibration import _levels, _ordered_outcome_leximin, check_against_oracle

ACC = 1e-5
LO, HI = 0.5, 2.0


@st.composite
def problems(draw):
    """Small problems: 0/1 margins plus a total, positive weights, off targets."""
    seed = draw(st.integers(0, 2**32 - 1))
    rng = np.random.default_rng(seed)
    m = draw(st.integers(1, 4))
    n = draw(st.integers(3, 10))
    A = (rng.random((m, n)) < 0.5).astype(float)
    A = np.vstack([A, np.ones(n)])
    A = A[A.sum(axis=1) > 0]
    w0 = rng.uniform(0.5, 3.0, n)
    b = A @ w0 * rng.uniform(0.5, 2.0, len(A))
    return A, b, w0


def _scaled_misses(result, b):
    return np.abs(result.residuals) / np.abs(b)


def _sorted_changes(result, w0):
    return np.sort(np.abs(result.w / w0 - 1.0))


SETTINGS = settings(max_examples=60, deadline=None)


@SETTINGS
@given(problems(), st.randoms(use_true_random=False))
def test_permuting_units_changes_nothing_that_matters(problem, rnd):
    A, b, w0 = problem
    perm = np.array(rnd.sample(range(len(w0)), len(w0)))

    base = leximin_weights(A, b, w0, min_ratio=LO, max_ratio=HI)
    moved = leximin_weights(A[:, perm], b, w0[perm], min_ratio=LO, max_ratio=HI)

    assert np.allclose(_scaled_misses(base, b), _scaled_misses(moved, b), atol=ACC)
    assert np.allclose(
        _sorted_changes(base, w0), _sorted_changes(moved, w0[perm]), atol=ACC
    )


@SETTINGS
@given(problems(), st.randoms(use_true_random=False))
def test_permuting_margins_permutes_the_misses(problem, rnd):
    A, b, w0 = problem
    perm = np.array(rnd.sample(range(len(b)), len(b)))

    base = leximin_weights(A, b, w0, min_ratio=LO, max_ratio=HI)
    moved = leximin_weights(A[perm], b[perm], w0, min_ratio=LO, max_ratio=HI)

    assert np.allclose(
        _scaled_misses(base, b)[perm], _scaled_misses(moved, b[perm]), atol=ACC
    )


@SETTINGS
@given(problems(), st.integers(0, 9))
def test_splitting_a_unit_in_two_changes_nothing(problem, k):
    A, b, w0 = problem
    k %= len(w0)
    a_more = np.hstack([A, A[:, [k]]])
    w0_more = np.r_[w0, w0[k] / 2]
    w0_more[k] /= 2

    base = leximin_weights(A, b, w0, min_ratio=LO, max_ratio=HI)
    split = leximin_weights(a_more, b, w0_more, min_ratio=LO, max_ratio=HI)

    assert np.allclose(_scaled_misses(base, b), _scaled_misses(split, b), atol=ACC)
    assert np.isclose(base.t, split.t, atol=ACC)


@SETTINGS
@given(problems(), st.floats(0.01, 100.0))
def test_rescaling_targets_and_weights_rescales_the_answer(problem, c):
    A, b, w0 = problem

    base = leximin_weights(A, b, w0, min_ratio=LO, max_ratio=HI)
    scaled = leximin_weights(A, c * b, c * w0, min_ratio=LO, max_ratio=HI)

    assert np.allclose(_scaled_misses(base, b), _scaled_misses(scaled, c * b), atol=ACC)
    assert np.allclose(scaled.w / (c * w0), base.w / w0, atol=10 * ACC)


@SETTINGS
@given(problems())
def test_adding_a_zero_weight_unit_changes_nothing(problem):
    A, b, w0 = problem
    a_more = np.hstack([A, np.ones((len(A), 1))])
    w0_more = np.r_[w0, 0.0]

    base = leximin_weights(A, b, w0, min_ratio=LO, max_ratio=HI)
    padded = leximin_weights(a_more, b, w0_more, min_ratio=LO, max_ratio=HI)

    assert padded.w[-1] == 0.0
    assert np.allclose(_scaled_misses(base, b), _scaled_misses(padded, b), atol=ACC)


@SETTINGS
@given(problems())
def test_misses_match_the_independent_oracle(problem):
    A, b, w0 = problem
    check_against_oracle(A, b, w0, np.abs(b), LO, HI)


@SETTINGS
@given(problems())
def test_weight_changes_match_the_independent_oracle(problem):
    """The weight stage's relative changes are leximin-optimal per unit.

    The oracle holds every margin exactly where the engine's weight stage
    does, at its leximin level plus the engine's tolerance, and computes the
    leximin vector of |w_i / w0_i - 1| over units by the ordered-outcome
    method, sharing no code with the saturation loop.
    """
    A, b, w0 = problem
    s = np.abs(b)

    result = leximin_weights(A, b, w0, min_ratio=LO, max_ratio=HI)

    levels = _levels(A, b, w0, s, LO, HI)
    radius = (levels + calibration._tol(levels, b / s)) * s
    extra = (np.vstack([A, -A]), np.r_[b + radius, -b + radius])
    expected = _ordered_outcome_leximin(
        np.diag(1 / w0), np.ones(len(w0)), w0 * LO, w0 * HI, extra=extra
    )
    got = np.sort(np.abs(result.w / w0 - 1))[::-1]
    assert np.allclose(got, expected, atol=1e-4)
